---
title: "NutriCare Microbiome Sample Update"
author: "Dan Spakowicz"
date: "`r Sys.Date()`"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path("sample-updates", paste0(Sys.Date(), '_sample-update.html'))) })
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r}
x <- read.table("../data/raw/2021-05-27_labii_samples_export.tsv",
                sep = "\t",
                header = TRUE)
```

```{r}
reformatDates <- function(x) {
  as.Date(x, format = "%F")
}

y <- 
  x %>%
  select(name, Date.Sample.Collected, date_processed, sample_id, record_id, is_suspect) %>%
  mutate_at(c("date_processed", "Date.Sample.Collected"), reformatDates) %>%
  mutate(site = gsub("^(\\d).*", "\\1", record_id))

head(y)
```

```{r}
samples <- 
  y %>%
  separate(sample_id, into = c("subjectid", "date", "tube")) %>%
  select(subjectid, Date.Sample.Collected, site) %>%
  unique %>%
  arrange(Date.Sample.Collected) %>% 
  mutate(n = seq(1, nrow(.))) %>%
  group_by(subjectid) %>%
  mutate(time.point = row_number()) %>%
  mutate(time.point = as.factor(time.point)) %>%
  mutate(site = gsub("^(\\d).*", "\\1", subjectid))

samples
```

```{r}
samples %>%
  ggplot(aes(x = Date.Sample.Collected, y = n)) +
  geom_point(aes(color = time.point)) +
  theme_bw() +
  annotate("text", 
           x = as.Date("2021-02-01", format = "%F"),
           y = 20,
           label = paste0("total number of samples = ", nrow(samples)))
```

```{r}
samples %>%
  ggplot(aes(x = Date.Sample.Collected, y = subjectid)) +
  geom_point(aes(color = time.point)) +
  theme_bw()
```

```{r}
samples %>%
  group_by(site) %>%
  count(site) %>%
  ggplot(aes(x = site, y = n)) +
  geom_bar(stat = "identity", aes(fill = site), show.legend = FALSE) +
  theme_bw() 
```


```{r, message=FALSE}
y %>%
  mutate(transit = date_processed - Date.Sample.Collected) %>%
  ggplot(aes(x = transit)) +
  geom_histogram(aes(fill = site)) +
  theme_bw() +
  labs(x = "Transit Time (days)")
```
